services:
  - type: web
    name: walletconnect-flask
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    autoDeploy: true
    https://github.com/eliot-pentest/walletconnect-flask
